const ACCESS_TOKEN_EXPIRED = "ACCESS_TOKEN_EXPIRED";
const EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS";
const IF_USER_EXISTS_YOU_WILL_RECEIVE_AN_EMAIL =
  "IF_USER_EXISTS_YOU_WILL_RECEIVE_AN_EMAIL";
const USER_DOES_NOT_EXISTS = "USER_DOES_NOT_EXISTS";
const USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS";
const USER_CREATED_SUCCESSFULLY = "USER_CREATED_SUCCESSFULLY";
const INCORRECT_USERNAME_OR_PASSWORD = "INCORRECT_USERNAME_OR_PASSWORD";
const INCORRECT_PASSWORD = "INCORRECT_PASSWORD";
const INCORRET_AMOUNT = "INCORRET_AMOUNT";
const UNAUTHORIZED = "UNAUTHORIZED";
const NO_TOKEN_PROVIDED = "NO_TOKEN_PROVIDED";
const REFRESH_TOKEN_IS_REQUIRED = "REFRESH_TOKEN_IS_REQUIRED";
const REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED";
const RENT_AMOUNT_HAS_BEEN_UPDATED = "RENT_AMOUNT_HAS_BEEN_UPDATED";
const RENT_PAID_SUCCESSFULLY = "RENT_PAID_SUCCESSFULLY";
const UNEXPECTED = "UNEXPECTED";
const VERIFY_EMAIL = "VERIFY_EMAIL";
const PROPERTY_CREATED_SUCCESSFULLY = "PROPERTY_CREATED_SUCCESSFULLY";
const PROPERTY_HAS_ALREADY_A_LEASE = "PROPERTY_HAS_ALREADY_A_LEASE";
const PROPERTY_HAS_A_PENDING_LEASE = "PROPERTY_HAS_A_PENDING_LEASE";
const PROPERTY_DOES_NOT_EXISTS = "PROPERTY_DOES_NOT_EXISTS";
const LEASE_CREATED_SUCCESSFULLY = "LEASE_CREATED_SUCCESSFULLY";
const LEASE_IS_STOPPED = "LEASE_IS_STOPPED";
const LEASE_HAS_BEEN_SUCCESSFULLY_STARTED =
  "LEASE_HAS_BEEN_SUCCESSFULLY_STARTED";
const LEASE_HAS_BEEN_SUCCESSFULLY_RENEWED =
  "LEASE_HAS_BEEN_SUCCESSFULLY_RENEWED";
const LEASE_HAS_BEEN_SUCCESSFULLY_STOPPED =
  "LEASE_HAS_BEEN_SUCCESSFULLY_STOPPED";
const LEASE_HAS_BEEN_ALREADY_STARTED = "LEASE_HAS_BEEN_ALREADY_STARTED";
const LEASE_END_DATE_SHOULD_BE_GREATER_THAN_START_DATE =
  "LEASE_END_DATE_SHOULD_BE_GREATER_THAN_START_DATE";
const LEASE_START_DATE_SHOULD_NOT_BE_LOWER_THAN_TODAY =
  "LEASE_START_DATE_SHOULD_NOT_BE_LOWER_THAN_TODAY";
const LEASE_START_RENEWAL_DATE_SHOULD_NOT_BE_LOWER_THAN_PREVIOUS_END_DATE =
  "LEASE_START_RENEWAL_DATE_SHOULD_NOT_BE_LOWER_THAN_PREVIOUS_END_DATE";
const DUPLICATED_PROPERTY = "DUPLICATED_PROPERTY";
const SUCCESS = "SUCCESS";
const NO_DATA_FOUND = "NO_DATA_FOUND";
const NO_PROPERTY_FOUND = "NO_PROPERTY_FOUND";
const NO_LEASE_FOUND = "NO_LEASE_FOUND";
const NO_PROPERTIES_FOUND = "NO_PROPERTIES_FOUND";
const NO_PAYMENT_FOUND = "NO_PAYMENT_FOUND";
const PROPERTY_UPDATED = "PROPERTY_UPDATED";
const THERE_ARE_STILL_ARREARS = "THERE_ARE_STILL_ARREARS";
const YOU_ARE_THE_LANDLORD_OF_THIS_PROPERTY =
  "YOU_ARE_THE_LANDLORD_OF_THIS_PROPERTY";
const YOU_ARE_NOT_THE_LANDLORD_OF_THIS_PROPERTY =
  "YOU_ARE_NOT_THE_LANDLORD_OF_THIS_PROPERTY";

module.exports.ACCESS_TOKEN_EXPIRED = ACCESS_TOKEN_EXPIRED;
module.exports.EMAIL_ALREADY_EXISTS = EMAIL_ALREADY_EXISTS;
module.exports.USERNAME_ALREADY_EXISTS = USERNAME_ALREADY_EXISTS;
module.exports.USER_CREATED_SUCCESSFULLY = USER_CREATED_SUCCESSFULLY;
module.exports.INCORRECT_USERNAME_OR_PASSWORD = INCORRECT_USERNAME_OR_PASSWORD;
module.exports.INCORRET_AMOUNT = INCORRET_AMOUNT;
module.exports.UNAUTHORIZED = UNAUTHORIZED;
module.exports.NO_TOKEN_PROVIDED = NO_TOKEN_PROVIDED;
module.exports.REFRESH_TOKEN_IS_REQUIRED = REFRESH_TOKEN_IS_REQUIRED;
module.exports.REFRESH_TOKEN_EXPIRED = REFRESH_TOKEN_EXPIRED;
module.exports.RENT_AMOUNT_HAS_BEEN_UPDATED = RENT_AMOUNT_HAS_BEEN_UPDATED;
module.exports.RENT_PAID_SUCCESSFULLY = RENT_PAID_SUCCESSFULLY;
module.exports.UNEXPECTED = UNEXPECTED;
module.exports.VERIFY_EMAIL = VERIFY_EMAIL;
module.exports.PROPERTY_CREATED_SUCCESSFULLY = PROPERTY_CREATED_SUCCESSFULLY;
module.exports.PROPERTY_HAS_ALREADY_A_LEASE = PROPERTY_HAS_ALREADY_A_LEASE;
module.exports.PROPERTY_HAS_A_PENDING_LEASE = PROPERTY_HAS_A_PENDING_LEASE;
module.exports.PROPERTY_DOES_NOT_EXISTS = PROPERTY_DOES_NOT_EXISTS;
module.exports.LEASE_CREATED_SUCCESSFULLY = LEASE_CREATED_SUCCESSFULLY;
module.exports.LEASE_IS_STOPPED = LEASE_IS_STOPPED;
module.exports.LEASE_HAS_BEEN_SUCCESSFULLY_STARTED =
  LEASE_HAS_BEEN_SUCCESSFULLY_STARTED;
module.exports.LEASE_HAS_BEEN_SUCCESSFULLY_RENEWED =
  LEASE_HAS_BEEN_SUCCESSFULLY_RENEWED;
module.exports.LEASE_HAS_BEEN_SUCCESSFULLY_STOPPED =
  LEASE_HAS_BEEN_SUCCESSFULLY_STOPPED;
module.exports.LEASE_HAS_BEEN_ALREADY_STARTED = LEASE_HAS_BEEN_ALREADY_STARTED;
module.exports.LEASE_END_DATE_SHOULD_BE_GREATER_THAN_START_DATE =
  LEASE_END_DATE_SHOULD_BE_GREATER_THAN_START_DATE;
module.exports.LEASE_START_DATE_SHOULD_NOT_BE_LOWER_THAN_TODAY =
  LEASE_START_DATE_SHOULD_NOT_BE_LOWER_THAN_TODAY;
module.exports.LEASE_START_RENEWAL_DATE_SHOULD_NOT_BE_LOWER_THAN_PREVIOUS_END_DATE =
  LEASE_START_RENEWAL_DATE_SHOULD_NOT_BE_LOWER_THAN_PREVIOUS_END_DATE;
module.exports.DUPLICATED_PROPERTY = DUPLICATED_PROPERTY;
module.exports.SUCCESS = SUCCESS;
module.exports.NO_DATA_FOUND = NO_DATA_FOUND;
module.exports.THERE_ARE_STILL_ARREARS = THERE_ARE_STILL_ARREARS;
module.exports.NO_PROPERTY_FOUND = NO_PROPERTY_FOUND;
module.exports.NO_LEASE_FOUND = NO_LEASE_FOUND;
module.exports.NO_PROPERTIES_FOUND = NO_PROPERTIES_FOUND;
module.exports.NO_PAYMENT_FOUND = NO_PAYMENT_FOUND;
module.exports.PROPERTY_UPDATED = PROPERTY_UPDATED;
module.exports.YOU_ARE_THE_LANDLORD_OF_THIS_PROPERTY =
  YOU_ARE_THE_LANDLORD_OF_THIS_PROPERTY;
module.exports.YOU_ARE_NOT_THE_LANDLORD_OF_THIS_PROPERTY =
  YOU_ARE_NOT_THE_LANDLORD_OF_THIS_PROPERTY;
module.exports.USER_DOES_NOT_EXISTS = USER_DOES_NOT_EXISTS;
module.exports.IF_USER_EXISTS_YOU_WILL_RECEIVE_AN_EMAIL =
  IF_USER_EXISTS_YOU_WILL_RECEIVE_AN_EMAIL;
module.exports.INCORRECT_PASSWORD = INCORRECT_PASSWORD;
